### ISSUE TITLE
Some goals are generated on the obstacles

### ISSUE THREAD

**Issue by srane96** [KrishnaBhatu/warehouse_manager#1]

**Comment by KrishnaBhatu** [comment]
@srane96 Could you please post the metadata file of your map?

**Comment by srane96** [comment]
map_load_time: 
  secs: 1585504366
  nsecs: 415358729
resolution: 0.10000000149
width: 1006
height: 605
origin: 
  position: 
    x: 0.0
    y: 0.0
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0

**Comment by KrishnaBhatu** [comment]
Thanks!

**Comment by KrishnaBhatu** [comment]
@srane96 Verify new goals from https://github.com/KrishnaBhatu/warehouse_manager/tree/kb_new_goals this branch

**Comment by srane96** [comment]
New goals are in pixels. But our robots are operating in meters environment (100 X 60 meters).

**Comment by KrishnaBhatu** [comment]
Changed the goals to meters @srane96
